baseURL             = "https://rahulmanthena.appspot.com/"
canonifyurls        = false
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa-eh_modded"
author              = "Rahul Manthena"
title               = "My Adventures in Developerland"
pluralizelisttitles = false
builddrafts         = false

googleAnalytics    = "UA-131327365-1"
disqusshortname     = "rahulmanthena" # Comment out to disable Disqus.

# Remove files from destination not found in static directories
cleandestinationdir = true

# Syntax highlighting using Pygments
pygmentsCodeFences  = true       # This applies to Chroma too.
pygmentsStyle       = "monokai"
enableEmoji         = true
# pygmentsOptions     = "linenos=true"
enableRobotsTXT     = true

[permalinks]
blog                = "blog/:slug/"

[params]
latestpostcount = 5
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
#copyright = "Copyright © 2019 Rahul Manthena"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = ""
faviconfile = ""
highlightjs = false
progressively = true
share = true
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
github = "rahulmanthena"
email = "rahulmanthena@gmail.com"
twitter = "rahulmanthena"
facebook = "rahulmanthena"
instagram = "manthenarahul"
#social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "rahulmanthena/blog/tree/master"
small_banner_logo = false

[params.colors]
identifier = "#ff5042"
identifier_dark = "#ffc549"
trivial = "#ff5042"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"